apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: sabre-gke
  git:
    syncRepo: git@github.com:EcaterinaGr/unicredit-configsync.git
    syncBranch: main
    secretType: ssh
    policyDir: cluster_config
